framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
            #async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                        max_retries: 3
                        multiplier: 2
            async_delayed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                options:
                    exchange:
                        name: emails
                    queues:
                        messegase_emails: ~
            test_email: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
            App\Message\MailMessage: async
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async_delayed
